name: minigpg
channels:
  - conda-forge
dependencies:
  - make
  - cmake=3.17
  - python=3.8
  - eigen=3.4.0
  - swig==4.0.2
  - python-devtools==0.9.0
  - pip
  - pip:
    - numpy
    - scikit-learn
    - sympy
    - pandas
    - setuptools
    - matplotlib
